#!/bin/bash

. /opt/helpers

CNFSUFFIX=icingaweb2_vspheredb
mysql_cnf_init_section \
	"${CNFSUFFIX}" \
	"${ICINGAWEB2_VSPHEREDB_MYSQL_HOST}" \
	"${ICINGAWEB2_VSPHEREDB_MYSQL_PORT}" \
	"${ICINGAWEB2_VSPHEREDB_MYSQL_USER}" \
	"${ICINGAWEB2_VSPHEREDB_MYSQL_DATA}" \
	"${ICINGAWEB2_VSPHEREDB_MYSQL_PASS}"
mysql_wait \
	"${ICINGAWEB2_VSPHEREDB_MYSQL_HOST}" \
	"${ICINGAWEB2_VSPHEREDB_MYSQL_PORT}"

if evaluate_boolean "${ICINGA2_FEATURE_VSPHEREDB}"; then
		echo "=> Enabling Icingaweb2 VSphereDB module"

    # Enable dependencies and the VSphereDB module
    icingacli module enable incubator
    icingacli module enable vspheredb

    # Create MySQL user
	if [ "${ICINGAWEB2_VSPHEREDB_MYSQL_HOST}" == "localhost" ]; then
		mysql_root <<-END
		  CREATE DATABASE IF NOT EXISTS ${ICINGAWEB2_VSPHERE_MYSQL_DATA}
		    CHARACTER SET 'utf8mb4' COLLATE utf8mb4_bin;
		  GRANT ALL
		    ON ${ICINGAWEB2_VSPHEREDB_MYSQL_DATA}.*
		    TO '${ICINGAWEB2_VSPHEREDB_MYSQL_USER}'@'localhost'
		    IDENTIFIED BY '${ICINGAWEB2_VSPHEREDB_MYSQL_PASS}';
		END
    elif [ -n "$MYSQL_ROOT_PASSWORD:-}" ]; then
   		mysql_root <<-END
		  CREATE DATABASE IF NOT EXISTS ${ICINGAWEB2_VSPHEREDB_MYSQL_DATA}
		    CHARACTER SET 'utf8mb4' COLLATE utf8mb4_bin;
		  GRANT ALL
		    ON ${ICINGAWEB2_VSPHEREDB_MYSQL_DATA}.*
		    TO '${ICINGAWEB2_VSPHEREDB_MYSQL_USER}'@'%'
		    IDENTIFIED BY '${ICINGAWEB2_VSPHEREDB_MYSQL_PASS}';
		END
    fi

    mysql_test_credentials

    mysql_user \
        < /usr/local/share/icingaweb2/modules/vspheredb/schema/mysql.sql \
        >> /var/log/icingaweb2/vsphere-schema.log \
        2>&1 || true

    # Set up resource
    ini_set /etc/icingaweb2/resources.ini vspheredb host       "${ICINGAWEB2_VSPHEREDB_MYSQL_HOST}"
    ini_set /etc/icingaweb2/resources.ini vspheredb port       "${ICINGAWEB2_VSPHEREDB_MYSQL_PORT}"
    ini_set /etc/icingaweb2/resources.ini vspheredb username   "${ICINGAWEB2_VSPHEREDB_MYSQL_USER}"
    ini_set /etc/icingaweb2/resources.ini vspheredb password   "${ICINGAWEB2_VSPHEREDB_MYSQL_PASS}"
    ini_set /etc/icingaweb2/resources.ini vspheredb dbname     "${ICINGAWEB2_VSPHEREDB_MYSQL_DATA}"
    ini_set /etc/icingaweb2/resources.ini vspheredb type       "db"
		ini_set /etc/icingaweb2/resources.ini vspheredb db			   "mysql"
		ini_set /etc/icingaweb2/resources.ini vspheredb charset    "utf8mb4"
		ini_set /etc/icingaweb2/resources.ini vspheredb persistent "0"

    # Configure backend
		mkdir -p /etc/icingaweb2/modules/vspheredb
		chown -R www-data:icingaweb2 /etc/icingaweb2/modules/vspheredb
		#touch /etc/icingaweb2/modules/vspheredb/config.ini
    ini_set /etc/icingaweb2/modules/vspheredb/config.ini db resource "vspheredb"

else
    # Actively disable VSphereDB module
    icingacli module disable vspheredb || true

fi