#!/bin/bash

. /opt/helpers

CNFSUFFIX=icingaweb2_x509
mysql_cnf_init_section \
	"${CNFSUFFIX}" \
	"${ICINGAWEB2_X509_MYSQL_HOST}" \
	"${ICINGAWEB2_X509_MYSQL_PORT}" \
	"${ICINGAWEB2_X509_MYSQL_USER}" \
	"${ICINGAWEB2_X509_MYSQL_DATA}" \
	"${ICINGAWEB2_X509_MYSQL_PASS}"
mysql_wait \
	"${ICINGAWEB2_X509_MYSQL_HOST}" \
	"${ICINGAWEB2_X509_MYSQL_PORT}"

if evaluate_boolean "${ICINGA2_FEATURE_X509}"; then
		echo "=> Enabling Icingaweb2 X.509 module"

    # Enable dependencies and the x509 module
    icingacli module enable ipl
    icingacli module enable react
    icingacli module enable x509

    # Create MySQL user
	if [ "${ICINGAWEB2_X509_MYSQL_HOST}" == "localhost" ]; then
		mysql_root <<-END
		  CREATE DATABASE IF NOT EXISTS ${ICINGAWEB2_X509_MYSQL_DATA}
		    CHARACTER SET 'utf8';
		  GRANT ALL
		    ON ${ICINGAWEB2_X509_MYSQL_DATA}.*
		    TO '${ICINGAWEB2_X509_MYSQL_USER}'@'localhost'
		    IDENTIFIED BY '${ICINGAWEB2_X509_MYSQL_PASS}';
		END
    elif [ -n "$MYSQL_ROOT_PASSWORD:-}" ]; then
   		mysql_root <<-END
		  CREATE DATABASE IF NOT EXISTS ${ICINGAWEB2_X509_MYSQL_DATA}
		    CHARACTER SET 'utf8';
		  GRANT ALL
		    ON ${ICINGAWEB2_X509_MYSQL_DATA}.*
		    TO '${ICINGAWEB2_X509_MYSQL_USER}'@'%'
		    IDENTIFIED BY '${ICINGAWEB2_X509_MYSQL_PASS}';
		END
    fi

    mysql_test_credentials

    mysql_user \
        < /usr/local/share/icingaweb2/modules/x509/etc/schema/mysql.schema.sql \
        >> /var/log/icingaweb2/x509-schema.log \
        2>&1 || true

    # Set up resource
    ini_set /etc/icingaweb2/resources.ini x509_db host     "${ICINGAWEB2_X509_MYSQL_HOST}"
    ini_set /etc/icingaweb2/resources.ini x509_db port     "${ICINGAWEB2_X509_MYSQL_PORT}"
    ini_set /etc/icingaweb2/resources.ini x509_db username "${ICINGAWEB2_X509_MYSQL_USER}"
    ini_set /etc/icingaweb2/resources.ini x509_db password "${ICINGAWEB2_X509_MYSQL_PASS}"
    ini_set /etc/icingaweb2/resources.ini x509_db dbname   "${ICINGAWEB2_X509_MYSQL_DATA}"
    ini_set /etc/icingaweb2/resources.ini x509_db type     "db"
		ini_set /etc/icingaweb2/resources.ini x509_db db			 "mysql"
		ini_set /etc/icingaweb2/resources.ini x509_db charset  "utf8"
		ini_set /etc/icingaweb2/resources.ini x509_db persistent "0"

    # Configure backend
		mkdir -p /etc/icingaweb2/modules/x509
		#touch /etc/icingaweb2/modules/x509/config.ini
    ini_set /etc/icingaweb2/modules/x509/config.ini backend resource "x509_db"

		# Import default CAs?
		if evaluate_boolean "${ICINGAWEB2_X509_IMPORT_DEFAULT_CAS}"; then
			echo "=> Import default CAs"
			icingacli x509 import --file /etc/ssl/certs/ca-certificates.crt
		fi
else
    # Actively disable X.509 module
    icingacli module disable x509 || true

fi